"$schema" = "./node_modules/wrangler/config-schema.json"
name = "emt-calculator-tools"
pages_build_output_dir = "dist"
compatibility_date = "2026-02-11"

# Environment-specific configuration
[env.production]
compatibility_date = "2026-02-11"

[env.preview]
compatibility_date = "2026-02-11"